### ISSUE TITLE
Increase <table> normalization and responsiveness

### ISSUE THREAD

**Issue by marcop135** [ZDroid/sanitize.css#1]
I love this project.

I suggest adding a little bit of extra-normalization and responsiveness to tables in this way:

``` css
table {
  max-width: 100%; /* avoid layout breaking */
  border-spacing: 0; /* avoid extra space between cells */
  background-color: transparent; /* override deprecated 'bgcolor' attribute */
} 
```
